name: remote-repo-sync
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0/6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  checks: read
  statuses: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
        BUILD_SCRIPT: npm install && npm run build