name: remote-repo-sync
on:
  workflow_dispatch:
#   schedule:
#   - cron: '0 0/6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  checks: read
  statuses: read

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Sync
      id: sync
      shell: bash
      run: | 
        
        curl -vv -A okhttp 'https://tv.iill.top/m3u/Gather' -o iill.m3u
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -F- <<EOF
        chore: sync iill; time: $(date '+%Y-%m-%d %H:%M:%S')
        EOF
        else
          echo "No changes to commit"
        fi
        git push origin main
        curl ifconfig.me
        curl --version
        uname -a
        exit 0