name: remote-repo-sync
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0/6 * * *'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read
  checks: read
  statuses: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Parse Sync Config
      id: parse-sync-config
      shell: bash
      run: | 
        curl ifconfig.me
        curl -vv -A okhttp 'https://tv.iill.top/m3u/Gather' -o iill.m3u
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        if [[ `git status --porcelain` ]]; then
          git add .
          git commit -F- <<EOF
        chore: sync iill
        EOF
        else
          echo "No changes to commit"
        fi
        git push origin main
        exit 0